openapi: 3.0.0
info:
  title: My Blog API
  version: 1.0.0
  description: API documentation for the blog application.
servers:
  - url: http://localhost:1337
paths:
  /blog-posts:
    get:
      summary: Get all blog posts
      responses:
        '200':
          description: A list of blog posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    content:
                      type: string
                    published_at:
                      type: string
                      format: date-time
                    category:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
  /categories:
    get:
      summary: Get all categories
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
